### ISSUE TITLE
Roadmap to v0.2

### ISSUE THREAD

**Issue by valkyrienyanko** [The-MMORPG-Project/Web-Server#2]
- [x] Website
    - [ ] Splash Page with Download Launcher Button
    - [ ] Register / Login Pages
- [x] MySQL Database
- [x] User Authentication
- [ ] Secure Transactions for Digital Goods
